approvedGitRepositories: null

compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: true

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

plugins:
  - .yarn/plugins/plugin-prepare.cjs

yarnPath: .yarn/releases/yarn-4.15.0.cjs
