compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: true

nodeLinker: node-modules

plugins:
  path: .yarn/plugins/plugin-setup-editor.cjs

yarnPath: .yarn/releases/yarn-4.0.2.cjs
