approvedGitRepositories:

compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: true

enableScripts: true

nodeLinker: node-modules

plugins:
  - .yarn/plugins/plugin-prepare.cjs

yarnPath: .yarn/releases/yarn-4.14.1.cjs
