approvedGitRepositories: null

compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: true

enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 0

plugins:
  - .yarn/plugins/plugin-prepare.cjs

yarnPath: .yarn/releases/yarn-4.16.0.cjs
