/**
 * @format
 * @flow
 */

export const foo2 = 2;
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
export const foo1 = 1;
