/**
 * @format
 * @flow
 */

import {foo1, foo2} from './foo';

(foo1: empty);
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
(foo2: empty);
