// Only testing babel parsing
// Do not add extra parsers here

runFormatTest(import.meta, ["babel", "babel-ts", "babel-flow"], {
  errors: {
    babel: ["flow.js", "typescript.js"],
    __babel_estree: ["flow.js", "typescript.js"],
    "babel-flow": [],
    "babel-ts": [],
    acorn: [
      "async-do-expressions.js",
      "decorator-auto-accessors.js",
      "decorators.js",
      "deferred-import-evaluation.js",
      "destructuring-private.js",
      "discard-binding.js",
      "do-expressions.js",
      "export-default-from.js",
      // "flow-comments.js",
      "flow.js",
      "function-bind.js",
      "function-bind-2.js",
      "function-sent.js",
      "module-blocks.js",
      "optional-chaining-assign.js",
      "partial-application.js",
      "pipeline-operator.js",
      "source-phase-imports.js",
      "throw-expressions.js",
      "typescript.js",
      "v8intrinsic.js",
    ],
    espree: [
      "async-do-expressions.js",
      "decorator-auto-accessors.js",
      "decorators.js",
      "deferred-import-evaluation.js",
      "destructuring-private.js",
      "discard-binding.js",
      "do-expressions.js",
      "export-default-from.js",
      // "flow-comments.js",
      "flow.js",
      "function-bind.js",
      "function-bind-2.js",
      "function-sent.js",
      "module-blocks.js",
      "optional-chaining-assign.js",
      "partial-application.js",
      "pipeline-operator.js",
      "source-phase-imports.js",
      "throw-expressions.js",
      "typescript.js",
      "v8intrinsic.js",
    ],
    meriyah: [
      "async-do-expressions.js",
      // "decorator-auto-accessors.js",
      // "decorators.js",
      // "deferred-import-evaluation.js",
      "destructuring-private.js",
      "discard-binding.js",
      "do-expressions.js",
      "export-default-from.js",
      // "flow-comments.js",
      "flow.js",
      "function-bind.js",
      "function-bind-2.js",
      "function-sent.js",
      "module-blocks.js",
      "optional-chaining-assign.js",
      "partial-application.js",
      "pipeline-operator.js",
      // "source-phase-imports.js",
      "throw-expressions.js",
      "typescript.js",
      "v8intrinsic.js",
    ],
    oxc: [
      "async-do-expressions.js",
      // "decorator-auto-accessors.js",
      // "decorators.js",
      // "deferred-import-evaluation.js",
      "destructuring-private.js",
      "discard-binding.js",
      "do-expressions.js",
      "export-default-from.js",
      // "flow-comments.js",
      "flow.js",
      "function-bind.js",
      "function-bind-2.js",
      "function-sent.js",
      "module-blocks.js",
      "optional-chaining-assign.js",
      "partial-application.js",
      "pipeline-operator.js",
      // "source-phase-imports.js",
      "throw-expressions.js",
      "typescript.js",
      "v8intrinsic.js",
    ],
    yuku: [
      "async-do-expressions.js",
      // "decorator-auto-accessors.js",
      // "decorators.js",
      // "deferred-import-evaluation.js",
      "destructuring-private.js",
      "discard-binding.js",
      "do-expressions.js",
      "export-default-from.js",
      // "flow-comments.js",
      "flow.js",
      "function-bind.js",
      "function-bind-2.js",
      "function-sent.js",
      "module-blocks.js",
      "optional-chaining-assign.js",
      "partial-application.js",
      "pipeline-operator.js",
      // "source-phase-imports.js",
      "throw-expressions.js",
      "typescript.js",
      "v8intrinsic.js",
    ],
  },
});
