const visitorKeys = {
  root: ["children"],
  document: ["head", "body"],
  documentHead: ["children"],
  documentBody: ["children"],
  directive: [],
  alias: [],
  blockLiteral: [],
  blockFolded: [],
  plain: [],
  quoteSingle: [],
  quoteDouble: [],
  mapping: ["children"],
  mappingItem: ["key", "value"],
  mappingKey: ["content"],
  mappingValue: ["content"],
  sequence: ["children"],
  sequenceItem: ["content"],
  flowMapping: ["children"],
  flowMappingItem: ["key", "value"],
  flowSequence: ["children"],
  flowSequenceItem: [],
  comment: [],
  tag: [],
  anchor: [],
};

export default visitorKeys;
