const visitorKeys = {
  "front-matter": [],
  root: ["children"],
  paragraph: ["children"],
  sentence: ["children"],
  word: [],
  whitespace: [],
  emphasis: [],
  strong: ["children"],
  delete: ["children"],
  inlineCode: [],
  wikiLink: [],
  link: [],
  image: [],
  blockquote: ["children"],
  heading: ["children"],
  code: [],
  html: [],
  list: ["children"],
  thematicBreak: [],
  linkReference: ["children"],
  imageReference: [],
  definition: [],
  footnote: ["children"],
  footnoteReference: [],
  footnoteDefinition: [],
  table: ["children"],
  tableCell: ["children"],
  break: [],
  liquidNode: [],
  importExport: [],
  esComment: [],
  jsx: [],
  math: [],
  inlineMath: [],
  tableRow: ["children"],
  listItem: ["children"],
};

export default visitorKeys;
