run_spec(import.meta, ["babel", "flow", "typescript"], {
  errors: {
    flow: [
      "for-await-using-of-comments.js",
      "invalid-duplicate-using-bindings.js",
      "invalid-script-top-level-using-binding.js",
      "using-declarations.js",
      // "valid-for-await-using-binding-escaped-of-of.js",
      // "valid-for-using-binding-escaped-of-of.js",
      "valid-module-block-top-level-using-binding.js",
      "valid-using-as-identifier-for-await-of.js",
      "valid-using-binding-basic.js",
      "valid-using-binding-escaped.js",
      "valid-using-binding-non-bmp.js",
      "valid-using-binding-using.js",
    ],
    typescript: [
      "for-await-using-of-comments.js",
      "invalid-duplicate-using-bindings.js",
      "invalid-script-top-level-using-binding.js",
      "using-declarations.js",
      // "valid-for-await-using-binding-escaped-of-of.js",
      // "valid-for-using-binding-escaped-of-of.js",
      "valid-module-block-top-level-using-binding.js",
      "valid-using-binding-basic.js",
      "valid-using-binding-escaped.js",
      "valid-using-binding-non-bmp.js",
      "valid-using-binding-using.js",
    ],
    espree: [
      "for-await-using-of-comments.js",
      "invalid-duplicate-using-bindings.js",
      "invalid-script-top-level-using-binding.js",
      "using-declarations.js",
      // "valid-for-await-using-binding-escaped-of-of.js",
      // "valid-for-using-binding-escaped-of-of.js",
      "valid-module-block-top-level-using-binding.js",
      "valid-using-binding-basic.js",
      "valid-using-binding-escaped.js",
      "valid-using-binding-non-bmp.js",
      "valid-using-binding-using.js",
    ],
    meriyah: [
      "for-await-using-of-comments.js",
      "invalid-duplicate-using-bindings.js",
      "invalid-script-top-level-using-binding.js",
      "using-declarations.js",
      // "valid-for-await-using-binding-escaped-of-of.js",
      // "valid-for-using-binding-escaped-of-of.js",
      "valid-module-block-top-level-using-binding.js",
      "valid-using-binding-basic.js",
      "valid-using-binding-escaped.js",
      "valid-using-binding-non-bmp.js",
      "valid-using-binding-using.js",
    ],
    acorn: [
      "for-await-using-of-comments.js",
      "invalid-duplicate-using-bindings.js",
      "invalid-script-top-level-using-binding.js",
      "using-declarations.js",
      // "valid-for-await-using-binding-escaped-of-of.js",
      // "valid-for-using-binding-escaped-of-of.js",
      "valid-module-block-top-level-using-binding.js",
      "valid-using-binding-basic.js",
      "valid-using-binding-escaped.js",
      "valid-using-binding-non-bmp.js",
      "valid-using-binding-using.js",
    ],
  },
});
