run_spec(
  {
    dirname: __dirname,
    snippets: [
      "{foo}",
      '{["foo"]:"bar"}',
      '{"foo": ~1}',
      '{"foo": false || "bar"}',
      '{"foo": undefined}',
      '{"foo": () => {}}',
      "packages\\the-hub\\cypress\\fixtures\\gridConfiguration.json",
      "1+2",
      "[,]",
      "[1,,2]",
      "{Infinity}",
      "{[key]: 1}",
      "{[key()]: 1}",
      "{['CallExpression']: 1}",
      "{['StringLiteral']: 1}",
      "{['string']: 1}",
      "{[1]: 1}",
      "{[Infinity]: 1}",
      "{[-Infinity]: 1}",
      "{[{key: 'value'}]: 1}",
      "{[[]]: 1}",
      "{[null]: 1}",
      "{key: +foo()}",
      "{key: void foo()}",
    ],
  },
  ["json", "json5", "json-stringify"]
);
