import loadBuiltinPlugins from "../../src/main/plugins/load-builtin-plugins.js";

// Snapshot to prevent mistakes
test("builtin parsers", async () => {
  const parserNames = (await loadBuiltinPlugins())
    .flatMap((plugin) => (plugin.parsers ? Object.keys(plugin.parsers) : []))
    .sort();

  expect(parserNames).toMatchInlineSnapshot(`
    [
      "__babel_estree",
      "__babel_estree",
      "__js_expression",
      "__js_expression",
      "__ng_action",
      "__ng_action",
      "__ng_binding",
      "__ng_binding",
      "__ng_directive",
      "__ng_directive",
      "__ng_interpolation",
      "__ng_interpolation",
      "__ts_expression",
      "__ts_expression",
      "__vue_event_binding",
      "__vue_event_binding",
      "__vue_expression",
      "__vue_expression",
      "__vue_ts_event_binding",
      "__vue_ts_event_binding",
      "__vue_ts_expression",
      "__vue_ts_expression",
      "acorn",
      "acorn",
      "angular",
      "babel",
      "babel",
      "babel-flow",
      "babel-flow",
      "babel-ts",
      "babel-ts",
      "css",
      "espree",
      "espree",
      "flow",
      "flow",
      "glimmer",
      "graphql",
      "hermes",
      "hermes",
      "html",
      "json",
      "json-stringify",
      "json5",
      "jsonc",
      "less",
      "lwc",
      "markdown",
      "mdx",
      "meriyah",
      "meriyah",
      "mjml",
      "oxc",
      "oxc",
      "oxc-ts",
      "oxc-ts",
      "remark",
      "scss",
      "typescript",
      "typescript",
      "vue",
      "yaml",
    ]
  `);
});
