import { parsing, transform } from "json-test-suite";

const SKIP = new Set([
  // Map keys must be unique
  // https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwA6ICGGkAYA0ABBtsgLS4C+aUhhI+IEADjAJbQDOyomATnwgB3AAr8E3FJgA2QzAE9ujAEZ9MYANZwYAZUwBbOABk2UOMgBmMznEYRlAKzhgYAdTXNkIZnzg2+AG7mKmqa2jrM6qYA5sgwfACutiA2+mxxiclwAB7McHxshrAyAPJ5ajAQfCIQnGzs0F4IACYMIDnlhQgwMgAq+VD8bH6W1sl1UNHScACKCRDwo9I2jA6c2Tox03ML5khWy8kAjvPwIoLMklicZGZwzfdt8Zhs0jEAwhD6+pheMtJtCZTOAAQRg8TYygSZ3yJjMSxWIAAFjB9NJXEj6n5ImA4DoJPU2AF6vIvGBOEoQAEkgBJKAPWA6MAFVgg+k6GDyaYI5I+WpwdyYTwoHx+fJBNotEoWOF7EDSCxtUz+GDnTDRH48xiRPj+LzyAwA7UFWCuNjNGBI5AADgIIF8JzYvjVGt++zGjB6yjNFqtSAATIwEjZephlJIDoi4PplPcHs0jJhJgl1XAAGJVH7gmJ-aEQECUShAA
  "object_same_key_unclear_values.json",
  // https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwA6ICGGkEYA0ABBtsgEwC+aUI+IEADjAJbQDOyomATtxAO4AFHgg4pMAG36YAnhzoAjbpjABrODADKmALZwAMsyhxkAM0ls4dCAoBWcMDADqyhshANucS9wBuJxWU1DU0GFSMAc2QYbgBXKxBLHWZouIS4AA8GOG5mPVhJAHls5RgIbkEINmYWaHcEABNaEEySvIQYSQAVHKgeZm8zCwTqqAiJOABFWIh4IYlLOls2DM1IienZkyRzBYSARxn4QT4GMSw2AFpjOAbb5pjMZglIgGEIHR1Md0kJZtHxnAAIIwGLMBSxY45QzGeaLEAACxgOgkTgRNW8YTAcE0ohqzF8NRk7jAbHkIF88QAklA7rBNGBckwgbTNDAZBM4QlPFU4C5MG4UJ5vDl-M1GoVTDDtiAJKZmkYfDATpgIl8uXQwtwfO4ZLo-prcrAnMwGjAEcgABwABjoXkOzC8KrV3x2wzonQUJrNFqQZDosUsXUwCjEu3hcB0Cludwa+kwY1iqrgADFyl9QZEfpCICAKBQgA
  "object_same_key_different_values.json",
  // https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwA6ICGGkEYA0ABBtsrgL5pQj4gQAOMAltAM7KiYBOXEA7gAVuCdikwAbPpgCe7WgCMumMAGs4MAMqYAtnAAyTKHGQAzCazi0I8gFZwwMAOpL6yEPS5wLXAG7GFSqrqGvTKhgDmyDBcAK6WIBbaTFGx8XAAHvRwXEy6sBIA8llKMBBcAhCsTMzQbggAJjQgGcW5CDASACrZUNxMXqbm8VVQ4eJwAIoxEPCD4ha0NqzpGhHjUzPGSGbz8QCO0-ACvPSiWKwAtEZw9TdN0ZhM4hEAwhDa2phuEuJNI2NwACCMGiTHkMSO2QMRjmCxAAAsYNpxI54dUvKEwHANCJqkwfNVpG4wKw5CAfHEAJJQW6wDRgHKMQE0jQwaTjWHxDyVODOTCuFAeLzZPxNBoFEzQrYgcQmJqGbwwY6YcKfTm0UJcbxuaQ6X4anKwRxMeoweHIAAcAAZaJ4DkxPMrVV9tkNaB15MbTeakAAmWgxCydTDyUQ7OFwbTyG63ep6TCjGIquAAMTKnxBEW+EIgIHI5CAA
  "object_same_key_same_value.json",
  // https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwA6ICGGkYEYYA0ABBtsvhgL5pQiEgQAOMAltAM7KiYBOvEAO4AFPgi4pMAG0GYAnlwZ5emMAGs4MAMqYAtnAAyrKHGQAzaRzgMIeAFZwwMAOoqmyEE15wrvAG6mSirqmlpMqsYA5sgwvACu1iBWuqwx8YlwAB5McLys+rDSAPI5KjAQvMIQHKxs0B4IACb0IFml+Qgw0gAquVB8rD7mlok1UJFScACKcRDww1JWDHYcmVpRkzNzpkgWi4kAjrPwwgJMElgcALQmcI13LbGYrFJRAMIQurqYHtJSLWMJnAAIIwWKsPBxE65IwmBZLEAACxguikzkRtR84TAcC04lqrD8tTkHjAHEUID8CQAklB7rAtGA8ixgXStDA5JN4YkvNU4K5MO4UF4fLkAi0mkUzLCdiApGYWsZfDBTphIt9uQxwrxfB45Hp-lq8rBnKxGjBEcgABwABgY3iOrG8qvVP12IwYXTwpvNlqQACYGHErN1MHgJHsEXBdHg7vdGgZMOM4mq4AAxCrfMFRX5QiAgKhUIA
  "y_object_duplicated_key_and_value.json",
  // https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwA6ICGGkYEYYA0ABBtshmBgL5pQiEgQAOMAltAM7KiYBOfCAHcACvwTcUmADZDMAT26M8fTGADWcGAGVMAWzgAZNlDjIAZjM5xGEPACs4YGAHVVzZCGZ841vgDczZVUNLW1mNRMAc2QYPgBXGxBrPTZYhKS4AA9mOD42A1gZAHlc1RgIPhEITjZ2aE8EABMGEGyygoQYGQAVPKh+Nl8LKyTaqCjpOABFeIh4EelrRntOLO1oqdn5syRLJaSARzn4EUFmSSxOAFpTOCb71rjMNmlogGEIPT1MTxlpVrjSZwACCMDibDw8VOeWMpkWyxAAAsYHppC4kXVfBEwHBtBI6mx-HV5J4wJwlCB-IkAJJQB6wbRgfKsEH07QweRTBFJbw1OBuTAeFDeXx5QKtZrFcxw3YgaTmVomPwwM6YKI-HmMCJ8PyeeT6AHa-KwFxsJowJHIAAcAAZGD5jmwfGqNb89qNGN08GaLVakAAmRjxaw9TB4ST7RFwPR4e4PJqGTATeLquAAMUqP3B0T+0IgIGo1CAA
  "y_object_duplicated_key.json",

  // Document contains trailing content not separated by a ... or --- line
  // https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBtAOugrgBjzzdETXfQX-+T8DNjsqBdS-EAGhAgAcYBLaAZ2SgAhgCcREAO4AFUQgEohAGwlCAngLYAjEULABrODADKQgLZwAMtyhxkAMyV84bCJoBWcMDADqOjshAOETgnEQA3Wy0dfUMjDl1rAHNkGBEsZxAnU24UtIy4AA8OOBFuc1glAHlinRgIESkIPm4eaACEABNWEEKasoQYJQAVEqhRbhD7RwzmqETFOABFLAh4KcUnNjc+AqMkheXV2yQHDYyARxX4KXEOeRAhPgBaGzgOt+7UoW5FJIBhCCmUxCAJKRTdWbzOAAQRgqW4miw1xKVhs602IAAFjBTIpvJiWiF4mA4EY5C1uGEWqoAmA+BoQGF0gBJKDvWBGMClLjQtlGGCqBbojJBJpwXxCfwoIIhEoRbqdSp2VHHECKOzdayhGA3ISJYHCtjxEShAKqMzgo2lWDebgdGCY5AADhwbGCl24wV1+pBJ2mbEGmlt9sdSAATGwsE4hkJNPJThi4KZNG93h0LEI5lg9XAAGL1YFwpKgpEQEAAX3LQA
  "i_string_utf16LE_no_BOM.json",

  // Maximum call stack size exceeded
  // https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBtdHNez3f8GFHEmlnkWVXU2130ONPMuYC6HnX3Pvf-AwUOEjRY8RMlTpM2XPkLFS5StVcQAGhAQADjACW0AM7JQAQwBOFiAHcACpYQmUZgDY2zATxNaARhbMwAGs4GABlMwBbOAAZfSg4ZAAzNyM4LQhfACs4MBgAdQCdZBAdCzg0iwA3RL8A4NCwnUD4gHNkGAsAV3SQNMj9Du7euAAPHTgLfWjYNwB5CYCYCAs7CCN9A2gShAATTRAxxemEGDcAFUmoS30K5NTejahW1zgARS6IeHvXNK0soyjMJtV4fL6JJApX69ACOn3gdmsOmcIDMRgAtAk4LtsQdOmZ9K42gBhCCRSJmEpuVwHJ4vOAAQRgnX0vi6CMmcQSPz+IAAFjBIq58nzNhVmmA4GEnJt9FVNp4SmAjD4QFUegBJKA42BhMBTPQM7VhGCeV483pldZwQpmYooMoVSY1A57OZJLkQkCuJIHeKVGCIsytCkWrTNCyVEqeKI08NTWD5fS7GB85AADgADFpynD9OUgyHKZCHlozr4kym00gAExaLppc5mXzOKG8uCRXzYnG7GJmZ5dYNwABiKwpzLaVPZEBAAF9Z0A
  "i_structure_500_nested_arrays.json",
]);

const BUGS = new Set([
  "y_object_string_unicode.json",
  "y_object_long_strings.json",
  "y_string_backslash_doublequotes.json",
]);

const cases = [...parsing, ...transform]
  .map(({ name, input, error }) => {
    if (error) {
      return;
    }

    if (SKIP.has(name) || BUGS.has(name)) {
      return;
    }

    return {
      name,
      code: input,
    };
  })
  .filter(Boolean);

runFormatTest(
  {
    importMeta: import.meta,
    snippets: cases,
  },
  ["yaml"],
);
