name: Internal ESLint Plugin Test

on:
  push:
    branches:
      - main
      - next
      - v*
      - patch-release
      - "!renovate/**"
    paths:
      - "scripts/tools/eslint-plugin-prettier-internal-rules/**"
      # This workflow file
      - ".github/workflows/eslint-rules.yml"
  pull_request:
    paths:
      - "scripts/tools/eslint-plugin-prettier-internal-rules/**"
      # This workflow file
      - ".github/workflows/eslint-rules.yml"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node.js
        uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # v7.1.0
        with:
          cache: "yarn"

      - name: Install Dependencies
        run: yarn --immutable

      - name: Test
        working-directory: scripts/tools/eslint-plugin-prettier-internal-rules
        run: yarn test-coverage
