name: Prevent File change

on:
  pull_request_target:
    paths:
      - "website/data/users.yml"

permissions:
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prevent-add-users:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Prevent file change
        uses: xalvarez/prevent-file-change-action@dbc67c205c9ed02aa39c497b422c24f364c3e8dd # v3.0.1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          pattern: website/data/users.yml
