name: Prevent File change

on:
  pull_request_target:
    paths:
      - "website/data/users.yml"

permissions:
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prevent-add-users:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Prevent file change
        uses: xalvarez/prevent-file-change-action@dbc67c205c9ed02aa39c497b422c24f364c3e8dd # v3.0.1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          pattern: website/data/users.yml
