name: Release Script Test

defaults:
  run:
    working-directory: scripts/release

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - patch-release
      - next
    paths:
      - "scripts/release/**"
      - ".github/workflows/release-script-test.yml"
  pull_request:
    paths:
      - "scripts/release/**"
      - ".github/workflows/release-script-test.yml"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node.js
        uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # v7.1.0
        with:
          # Minimal version the release script required
          node-version: "20"
          cache: "yarn"

      - name: Install Dependencies
        run: yarn --immutable

      - name: Test
        run: yarn test
